/*CREATE SCHEMA paymentsDB DEFAULT CHARACTER SET utf8 ;*/
DROP DATABASE IF EXISTS payments;
CREATE DATABASE IF NOT EXISTS payments;
USE payments;

CREATE  TABLE IF NOT EXISTS account (
  idAcc INT NOT NULL AUTO_INCREMENT ,
  numberAcc VARCHAR(34) NOT NULL ,
  balanceAcc DECIMAL(14,2) NOT NULL ,
  isBlockedAcc BIT NOT NULL,
  UNIQUE (numberAcc),
  PRIMARY KEY (idAcc)
  )ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE  TABLE IF NOT EXISTS client (
  idCl INT NOT NULL AUTO_INCREMENT ,
  emailCl VARCHAR(60) NOT NULL ,
  familyNameCl VARCHAR(80) NOT NULL,
  nameCl VARCHAR(80) NOT NULL,
  UNIQUE (emailCl),
  PRIMARY KEY (idCl)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS user (
  idUsr          INT         NOT NULL AUTO_INCREMENT,
  loginUsr       VARCHAR(20) NOT NULL,
  passUsr        VARCHAR(32),
  isAdminUsr    BIT  NOT NULL,
  FK_Usr_idCl INT  NULL,
  UNIQUE (loginUsr),
  PRIMARY KEY (idUsr),
  CONSTRAINT FK_Usr_idCl FOREIGN KEY (FK_Usr_idCl) REFERENCES client (idCl)
    ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE  TABLE IF NOT EXISTS creditCard (
  idCc INT NOT NULL AUTO_INCREMENT ,
  numberCc VARCHAR(16) NOT NULL ,
  FK_Cc_idCl INT NOT NULL ,
  FK_Cc_idAcc INT NOT NULL ,
  UNIQUE (numberCc),
  PRIMARY KEY (idCc),
  CONSTRAINT FK_Cc_idCl FOREIGN KEY (FK_Cc_idCl) REFERENCES client(idCl)
    ON UPDATE CASCADE ON DELETE RESTRICT ,
  CONSTRAINT FK_Cc_idAcc FOREIGN KEY (FK_Cc_idAcc) REFERENCES account(idAcc)
    ON UPDATE CASCADE ON DELETE RESTRICT
  )ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE  TABLE IF NOT EXISTS payment (
  idPay INT NOT NULL AUTO_INCREMENT ,
  timeStampPay TIMESTAMP NOT NULL ,
  amountPay DECIMAL(14,2) ,
  typePay TINYINT NOT NULL,
  FK_Pay_idSenderCl INT,
  FK_Pay_idSenderAcc INT,
  FK_Pay_idSenderCc INT ,
  FK_Pay_idRecipientAcc INT ,
  PRIMARY KEY (idPay),
  CONSTRAINT FK_Pay_idSenderCl FOREIGN KEY (FK_Pay_idSenderCl) REFERENCES client(idCl)
    ON UPDATE CASCADE ON DELETE RESTRICT ,
  CONSTRAINT FK_Pay_idSenderAcc FOREIGN KEY (FK_Pay_idSenderAcc) REFERENCES account(idAcc)
    ON UPDATE CASCADE ON DELETE RESTRICT ,
  CONSTRAINT FK_Pay_idSenderCc FOREIGN KEY (FK_Pay_idSenderCc) REFERENCES creditCard(idCc)
    ON UPDATE CASCADE ON DELETE RESTRICT ,
  CONSTRAINT FK_Pay_idRecipientAcc FOREIGN KEY (FK_Pay_idRecipientAcc) REFERENCES account(idAcc)
    ON UPDATE CASCADE ON DELETE RESTRICT
  )ENGINE=InnoDB DEFAULT CHARSET=utf8;





